### PR TITLE
advanced angular calculator repo add 

### PR DESCRIPTION
**Pull request by Dilshan1997**

### CODE REVIEW

**Comment by garg3133** [comment]
Hi @Dilshan1997, can you please also add a small description about your project in the json object you added. See #4.

**Comment by Dilshan1997** [comment]
hi @garg3133 ok bro

**Comment by Dilshan1997** [comment]
@garg3133 I add the description

**Comment by garg3133** [comment]
Thanks @Dilshan1997, merging it here.

**Pull request merged**
